### ISSUE TITLE
py.typed file is not included in Conda packages of starlette

### ISSUE THREAD

**Issue by Quogu** [conda-forge/starlette-feedstock#61]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: py.typed file is not included in Conda packages of starlette from conda-forge.

This is true for at least https://anaconda.org/conda-forge/starlette/0.16.0/download/noarch/starlette-0.16.0-pyhd8ed1ab_0.tar.bz2 and https://anaconda.org/conda-forge/starlette/0.14.2/download/noarch/starlette-0.14.2-pyhd8ed1ab_0.tar.bz2 - please can this be fixed, and a new build produced for 0.14.2 as well as newer versions? (This version is relevant because it's what `fastapi` currently uses.)
<br/>
Environment (<code>conda list</code>): Not applicable
<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ): Not applicable

**Comment by carlodri** [comment]
Is this still relevant? Which Python version are you using? I'm asking since it might be due to the fact that we are missing this dependency for `python < 3.8`:

https://github.com/encode/starlette/blob/2b3f5e6805095049dcea4faea6102b564348073a/setup.py#L42

**Comment by carlodri** [comment]
@Quogu please reopen if relevant
